import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The splash is generated by `flutter_native_splash` into native resources
/// that are easy to lose (a `flutter clean`, a merge, a regenerated project).
/// These checks fail loudly rather than shipping a white flash.
void main() {
  final pubspec = File('pubspec.yaml').readAsStringSync();

  group('splash configuration', () {
    test('declares the brand background and the glyph, in both themes', () {
      expect(pubspec, contains('flutter_native_splash:'));
      expect(pubspec, contains('color: "#B71C1C"'));
      expect(pubspec, contains('color_dark: "#1A0708"'));
      expect(pubspec, contains('image: assets/icon/splash_glyph.png'));
      expect(pubspec, contains('image_dark: assets/icon/splash_glyph.png'));
    });

    test('configures the Android 12+ splash API', () {
      expect(pubspec, contains('android_12:'));
      expect(pubspec, contains('icon_background_color: "#B71C1C"'));
    });

    test('carries no text: only a colour and an image are declared', () {
      // `flutter_native_splash` renders a branding image below the icon when
      // `branding:` is set. The design is glyph-only, so it must stay absent.
      expect(pubspec.contains('branding:'), isFalse);
    });

    test('the glyph asset exists and is square', () {
      final f = File('assets/icon/splash_glyph.png');
      expect(f.existsSync(), isTrue, reason: 'assets/icon/splash_glyph.png is missing');
      expect(f.lengthSync(), greaterThan(1000));
    });
  });

  group('generated native resources', () {
    test('iOS launch images exist for every scale', () {
      for (final name in ['LaunchImage.png', 'LaunchImage@2x.png', 'LaunchImage@3x.png']) {
        expect(File('ios/Runner/Assets.xcassets/LaunchImage.imageset/$name').existsSync(), isTrue,
            reason: '$name missing — re-run dart run flutter_native_splash:create');
      }
      expect(File('ios/Runner/Base.lproj/LaunchScreen.storyboard').existsSync(), isTrue);
    });

    test('Android styles point at the splash drawables', () {
      final light = File('android/app/src/main/res/values/styles.xml').readAsStringSync();
      final night = File('android/app/src/main/res/values-night/styles.xml').readAsStringSync();
      expect(light, contains('@drawable/launch_background'));
      expect(night, contains('@drawable/launch_background'));

      final v31 = File('android/app/src/main/res/values-v31/styles.xml');
      expect(v31.existsSync(), isTrue, reason: 'Android 12+ styles missing');
      final s = v31.readAsStringSync();
      expect(s, contains('windowSplashScreenBackground'));
      expect(s, contains('@drawable/android12splash'));
    });

    test('Android 12 splash drawables exist at several densities', () {
      for (final d in ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi']) {
        expect(File('android/app/src/main/res/drawable-$d/android12splash.png').existsSync(), isTrue,
            reason: 'drawable-$d/android12splash.png missing');
      }
    });
  });

  group('startup cost', () {
    test('the splash is not held open by hand', () {
      // Calling FlutterNativeSplash.preserve/remove would keep the native
      // splash on screen past the first frame — exactly the "perceptible
      // startup time" the design rules out.
      final main = File('lib/main.dart').readAsStringSync();
      expect(main.contains('FlutterNativeSplash'), isFalse,
          reason: 'the splash must hand over on the first frame, not be held');
    });
  });
}
