#!/usr/bin/env python3
"""Generate one launcher icon per city, in that city's own transit colour.

    tool/city_icons.py            # write every platform's assets
    tool/city_icons.py --check    # verify what is on disk matches, and write nothing

The art is the app's own `assets/icon/icon.png`; only the background changes. That keeps nine icons
recognisably the same app — the point is "this is your city's opentransit", not nine different apps —
and it means a redrawn glyph propagates everywhere by re-running this.

Reads the colours from the API's city YAMLs rather than a list kept here, so an icon cannot drift
from the brand colour the app itself draws with.

What it writes:

* `android/.../mipmap-<dpi>/ic_launcher_<city>.png`  — legacy bitmaps, pre-API-26 launchers
* `android/.../mipmap-anydpi-v26/ic_launcher_<city>.xml` — adaptive icon, shared foreground
* `android/.../values/colors.xml`                    — one background colour per city
* `ios/Runner/AlternateIcons/opentransit-<city>@2x.png` / `@3x.png`

iOS alternate icons must be loose files in the bundle, not entries in an asset catalog, and must be
listed in Info.plist. Both are done by `--check`'s sibling assertions rather than left to memory.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parents[1]
CITIES_DIR = ROOT.parent / "opentransit-api" / "cities"
SOURCE = ROOT / "assets" / "icon" / "icon.png"
ANDROID_RES = ROOT / "android" / "app" / "src" / "main" / "res"
IOS_ASSETS = ROOT / "ios" / "Runner" / "Assets.xcassets"

# Legacy launcher bitmaps, the densities flutter_launcher_icons already produces.
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
# The sizes iOS actually uses for an *alternate* icon: home screen, Spotlight, Settings and
# notifications. No 1024 marketing icon — only the primary needs one. Written out rather than left
# to the asset compiler's single-size generation, because this project deploys to iOS 15 and a
# missing size is a blank square on someone's home screen.
IOS_SIZES = [
    ("20x20", 2, 40), ("20x20", 3, 60),
    ("29x29", 2, 58), ("29x29", 3, 87),
    ("40x40", 2, 80), ("40x40", 3, 120),
    ("60x60", 2, 120), ("60x60", 3, 180),
]


def cities() -> dict[str, str]:
    """city id -> primary colour, straight from the API's own config."""
    out: dict[str, str] = {}
    for f in sorted(CITIES_DIR.glob("*.yaml")):
        if f.stem.startswith("_"):
            continue
        # A tiny read rather than a yaml dependency for the icon tool: the field is one line and
        # pinning PyYAML here would be the only reason this script needed a virtualenv.
        m = re.search(r"^branding:\s*$.*?^\s+primary_color:\s*[\"']?(#[0-9A-Fa-f]{6})",
                      f.read_text(), re.S | re.M)
        if m:
            out[f.stem] = m.group(1).upper()
    return out


def rgb(hex_colour: str) -> tuple[int, int, int]:
    h = hex_colour.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def is_light(colour: tuple[int, int, int]) -> bool:
    """Relative luminance, the WCAG way.

    Lisboa's transit yellow is #FFDD00. A white glyph on it is invisible, and an icon nobody can
    read on their own home screen is worse than the generic one.
    """
    def chan(c: int) -> float:
        s = c / 255
        return s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4

    r, g, b = (chan(c) for c in colour)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b > 0.4


def _bright(v: int) -> int:
    return 255 if v > 200 else 0


def glyph_mask(im: Image.Image) -> Image.Image:
    """The white artwork as a mask, so it can be repainted on any background.

    The same read `tool/store_graphics.py` uses, deliberately: if the glyph extraction ever changes,
    the store graphic and the launcher icon should change together or not at all.
    """
    r, g, b, a = im.convert("RGBA").split()
    near_white = r.point(_bright)
    for ch in (g, b):
        near_white = ImageChops.multiply(near_white, ch.point(_bright))
    return ImageChops.multiply(near_white, a)


def render(mask: Image.Image, colour: tuple[int, int, int], size: int) -> Image.Image:
    fg = (26, 26, 26) if is_light(colour) else (255, 255, 255)
    canvas = Image.new("RGB", mask.size, colour)
    canvas.paste(Image.new("RGB", mask.size, fg), (0, 0), mask)
    return canvas.resize((size, size), Image.LANCZOS)


def adaptive_xml(city: str) -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/city_icons.py. The foreground is shared with @mipmap/ic_launcher: nine
     icons of the same app, not nine apps. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/ic_launcher_background_{city}"/>
  <foreground>
      <inset
          android:drawable="@drawable/ic_launcher_foreground"
          android:inset="16%" />
  </foreground>
</adaptive-icon>
"""


def colours_xml(colours: dict[str, str], existing: str) -> str:
    """Keep whatever else lives in colors.xml and replace only the generated block."""
    generated = "\n".join(
        f'    <color name="ic_launcher_background_{c}">{h}</color>' for c, h in colours.items())
    block = (f"    <!-- city launcher backgrounds: generated by tool/city_icons.py -->\n"
             f"{generated}\n")
    marker = "    <!-- city launcher backgrounds: generated by tool/city_icons.py -->"
    if marker in existing:
        head = existing[:existing.index(marker)]
        tail = existing[existing.index("</resources>"):]
        return head + block + tail
    return existing.replace("</resources>", block + "</resources>")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="verify the assets on disk and write nothing")
    a = ap.parse_args()

    if not SOURCE.exists():
        print(f"no icon at {SOURCE}", file=sys.stderr)
        return 1
    colours = cities()
    if not colours:
        print(f"no city colours found under {CITIES_DIR}", file=sys.stderr)
        return 1

    src = Image.open(SOURCE)
    mask = glyph_mask(src)
    missing: list[str] = []

    for city, hexc in colours.items():
        colour = rgb(hexc)
        for dpi, size in DENSITIES.items():
            p = ANDROID_RES / f"mipmap-{dpi}" / f"ic_launcher_{city}.png"
            if a.check:
                if not p.exists():
                    missing.append(str(p.relative_to(ROOT)))
                continue
            p.parent.mkdir(parents=True, exist_ok=True)
            render(mask, colour, size).save(p, "PNG")

        xml = ANDROID_RES / "mipmap-anydpi-v26" / f"ic_launcher_{city}.xml"
        if a.check:
            if not xml.exists():
                missing.append(str(xml.relative_to(ROOT)))
        else:
            xml.parent.mkdir(parents=True, exist_ok=True)
            xml.write_text(adaptive_xml(city))

        iconset = IOS_ASSETS / f"AppIcon-{city}.appiconset"
        images = []
        for pts, scale, px in IOS_SIZES:
            name = f"Icon-{city}-{pts}@{scale}x.png"
            images.append({"size": pts, "idiom": "iphone", "filename": name, "scale": f"{scale}x"})
            f = iconset / name
            if a.check:
                if not f.exists():
                    missing.append(str(f.relative_to(ROOT)))
                continue
            iconset.mkdir(parents=True, exist_ok=True)
            # No alpha: iOS rejects an icon with transparency, and `render` already returns RGB.
            render(mask, colour, px).save(f, "PNG")
        contents = iconset / "Contents.json"
        if a.check:
            if not contents.exists():
                missing.append(str(contents.relative_to(ROOT)))
        else:
            contents.write_text(json.dumps(
                {"images": images, "info": {"version": 1, "author": "tool/city_icons.py"}},
                indent=2) + "\n")

    cx = ANDROID_RES / "values" / "colors.xml"
    if a.check:
        text = cx.read_text() if cx.exists() else ""
        for city, hexc in colours.items():
            if f'name="ic_launcher_background_{city}">{hexc}<' not in text:
                missing.append(f"colors.xml: ic_launcher_background_{city} = {hexc}")
    else:
        cx.write_text(colours_xml(colours, cx.read_text() if cx.exists() else
                                  '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n</resources>\n'))

    # Without this build setting the alternate icon sets compile to nothing and
    # `setAlternateIconName` fails at runtime with no hint as to why.
    names = " ".join(f"AppIcon-{c}" for c in colours)
    for cfg in ("Release.xcconfig", "Debug.xcconfig"):
        f = ROOT / "ios" / "Flutter" / cfg
        text = f.read_text() if f.exists() else ""
        line = f"ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES = {names}"
        want = ("ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS = YES\n" + line + "\n")
        if a.check:
            if line not in text:
                missing.append(f"ios/Flutter/{cfg}: {line}")
        elif line not in text:
            stripped = "\n".join(l for l in text.splitlines()
                                  if not l.startswith("ASSETCATALOG_COMPILER_"))
            f.write_text(stripped.rstrip() + "\n\n"
                         "// Alternate launcher icons, one per city. Generated by tool/city_icons.py:\n"
                         "// the names must match the .appiconset folders in Assets.xcassets, and the\n"
                         "// INCLUDE_ALL setting is what makes the compiler emit them at all.\n"
                         + want)

    if a.check:
        if missing:
            print("missing or stale:", file=sys.stderr)
            for m in missing:
                print(f"  {m}", file=sys.stderr)
            print("\nrun tool/city_icons.py to regenerate", file=sys.stderr)
            return 1
        print(f"{len(colours)} city icons present and matching")
        return 0

    for city, hexc in colours.items():
        fg = "dark" if is_light(rgb(hexc)) else "white"
        print(f"{city:13} {hexc}  glyph {fg}")
    print(f"\n{len(colours)} cities x ({len(DENSITIES)} android + 1 xml + {len(IOS_SIZES)} ios)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
